### ISSUE TITLE
Use stdin instead of writing a temp file

### ISSUE THREAD

**Issue by bdelespierre** [Magentron/laravel-blade-lint#2]
using `proc_open` we can pipe the content of the compiled string into `php -l` thus saving us the hassle of creating temporary files.

**Comment by bdelespierre** [comment]
Leave it to me I'll make a PR :+1:

**Comment by Magentron** [comment]
I'm not so sure whether this is actually an improvement as some installations may not have this function available (e.g. shared hosting environments where this has been disabled via [disable-functions](https://www.php.net/manual/en/ini.core.php#ini.disable-functions).

**Comment by bdelespierre** [comment]
Such environment won't have `exec` either when you think about it.

**Comment by bdelespierre** [comment]
And why would you want to run this script on shared hosting in the first place :man_shrugging:

**Comment by Magentron** [comment]
Makes sense, please submit the PR and I'll review it. Thanks in advance.

**Comment by bdelespierre** [comment]
On it.

**Comment by bdelespierre** [comment]
Here it is https://github.com/Magentron/laravel-blade-lint/pull/3

**Comment by Magentron** [comment]
Thanks! It's now publicly available as [1.0.5](https://packagist.org/packages/magentron/laravel-blade-lint#1.0.5)

**Comment by bdelespierre** [comment]
Great thanks :+1:
